### ISSUE TITLE
Fixed font settings | Unlabeled text fields

### ISSUE THREAD

**Issue by SicroAtGit** [tajmone/testing#1]
In the sample diagram I noticed that some text fields still have variable fonts (`sans` and `monospace`) and corrected them in commit c18006578683c50960f81b66bc30c6591088d912. Please create your diagrams again under Windows.

I wonder what is the purpose of the unlabeled text boxes in the diagram. Anyway, we can leave them in this test repository, but in the GitBuch repository we should think about them if they are necessary.

**Comment by tajmone** [comment]
Done!

I don't see the Linux diagrams you've generated. They should be in the repository with `Lnx` in their name (instead of `Win`),
